menu:
  - name: 首页
    url: /
    newTab: false
    subName: Home
  - name: 博文
    url: /categories/博文/
    newTab: false
    subName: Blog
  - name: 项目
    url: /categories/项目/
    newTab: false
    subName: Project
  - name: 笔记
    url: /categories/笔记/
    newTab: false
    subName: Notes

sections:
  - section: blog
  - section: project
  - section: notes
    
widgets:
  - clock
  - tags
  - net
  - saying

postWidget:
  - about
  - latest

favicon: /images/favicon.ico

#UserInfo
avatar: 
author: 
slogan: 

defaultThumb: /images/default.jpeg

#count and time
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false
  awl: 4
  wpm: 275
  suffix: 'min'